# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/apdrv/Unreal
GAMEPROJECTFILE =/home/apdrv/Документы/Unreal Projects/Call_Of_The_Forest/Call_Of_The_Forest.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	Call_Of_The_Forest-Linux-DebugGame  \
	Call_Of_The_Forest-Linux-Shipping  \
	Call_Of_The_Forest \
	Call_Of_The_ForestEditor-Linux-DebugGame  \
	Call_Of_The_ForestEditor-Linux-Shipping  \
	Call_Of_The_ForestEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Call_Of_The_ForestEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Call_Of_The_ForestEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

Call_Of_The_Forest-Linux-DebugGame:
	 $(PROJECTBUILD) Call_Of_The_Forest Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Call_Of_The_Forest-Linux-Shipping:
	 $(PROJECTBUILD) Call_Of_The_Forest Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Call_Of_The_Forest:
	 $(PROJECTBUILD) Call_Of_The_Forest Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

Call_Of_The_ForestEditor-Linux-DebugGame:
	 $(PROJECTBUILD) Call_Of_The_ForestEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Call_Of_The_ForestEditor-Linux-Shipping:
	 $(PROJECTBUILD) Call_Of_The_ForestEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Call_Of_The_ForestEditor:
	 $(PROJECTBUILD) Call_Of_The_ForestEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
